"""add page design

Revision ID: a79453452d83
Revises: b6a31168d666
Create Date: 2026-01-11 19:34:03.478783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a79453452d83'
down_revision: Union[str, None] = 'b6a31168d666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_data_source',
    sa.Column('application_id', sa.String(length=21), nullable=True, comment='所属应用ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='数据源编码（唯一标识）'),
    sa.Column('source_type', sa.String(length=20), nullable=True, comment='数据源类型: api/sql/static'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述说明'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('api_url', sa.String(length=500), nullable=True, comment='API地址，支持 {param} 占位符'),
    sa.Column('api_method', sa.String(length=10), nullable=True, comment='请求方法: GET/POST'),
    sa.Column('api_headers', sa.JSON(), nullable=True, comment='请求头配置'),
    sa.Column('api_body', sa.JSON(), nullable=True, comment='请求体模板（POST 时使用）'),
    sa.Column('api_timeout', sa.Integer(), nullable=True, comment='请求超时时间（秒）'),
    sa.Column('api_data_path', sa.String(length=100), nullable=True, comment='响应数据路径，如 data.list'),
    sa.Column('sql_content', sa.Text(), nullable=True, comment='SQL语句，使用 :param 作为参数占位符'),
    sa.Column('db_connection', sa.String(length=50), nullable=True, comment='数据库连接名称'),
    sa.Column('static_data', sa.JSON(), nullable=True, comment='静态数据（JSON 数组）'),
    sa.Column('params', sa.JSON(), nullable=True, comment='参数定义列表'),
    sa.Column('result_type', sa.String(length=20), nullable=True, comment='结果类型: list/tree/object/value/chart-*'),
    sa.Column('tree_config', sa.JSON(), nullable=True, comment='树形转换配置'),
    sa.Column('field_mapping', sa.JSON(), nullable=True, comment='字段映射配置'),
    sa.Column('chart_config', sa.JSON(), nullable=True, comment='图表配置'),
    sa.Column('cache_enabled', sa.Boolean(), nullable=True, comment='是否启用缓存'),
    sa.Column('cache_ttl', sa.Integer(), nullable=True, comment='缓存时间（秒）'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_data_source_application_id'), 'core_data_source', ['application_id'], unique=False)
    op.create_index(op.f('ix_core_data_source_code'), 'core_data_source', ['code'], unique=True)
    op.create_index(op.f('ix_core_data_source_is_deleted'), 'core_data_source', ['is_deleted'], unique=False)
    op.create_table('page_meta',
    sa.Column('name', sa.String(length=100), nullable=False, comment='页面名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='页面编码'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: draft/published'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('page_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='页面设计配置'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_page_meta_is_deleted'), 'page_meta', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_page_meta_status'), 'page_meta', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_meta_status'), table_name='page_meta')
    op.drop_index(op.f('ix_page_meta_is_deleted'), table_name='page_meta')
    op.drop_table('page_meta')
    op.drop_index(op.f('ix_core_data_source_is_deleted'), table_name='core_data_source')
    op.drop_index(op.f('ix_core_data_source_code'), table_name='core_data_source')
    op.drop_index(op.f('ix_core_data_source_application_id'), table_name='core_data_source')
    op.drop_table('core_data_source')
    # ### end Alembic commands ###
